config/routes.rb
Rails.application.routes.draw do
  resources :events
  root to: "posts#index"
  devise_for :users

  resources :users do
    member do
      post :follow
    end
    resources :comments, module: :users 
  end

  resources :posts do
    member do
      post :bookmark
    end
    resource :like, module: :posts
    resources :comments, module: :posts
  end


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :likes
  has_many :comments, as: :commentable
  has_many :events 
  validates :name, :email, :password, :password_confirmation, presence: true
  validates :email, uniqueness: {case_sensitive: true}
  validates :name, length: {minimum: 5, max: 20}
  validates :password, length: {minimum: 6}


  def likes?(post)
    post.likes.where(user_id: id).any?
  end

  def avatar_url
    hash = Digest::MD5.hexdigest(email)
    "http://www.gravatar.com/avatar/#{hash}"
  end
  
  def username
    "@#{name.gsub(/\s/, '')}"
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < CommentsController
  before_action :set_commentable

  private
  def set_commentable
    @commentable = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :follow]

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def follow
    current_user.events.create(action: "followed", eventable: @user)
    redirect_to  users_path
  end
  
  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/user/parameter_sanitizer.rb
class User::ParameterSanitizer < Devise::ParameterSanitizer
  def initialize(*)
    super
    permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
    permit(:sign_in, keys: [:email, :password])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li class="d-flex mb-1">
  <%= image_tag user.avatar_url, width: 40, height: 40, class: "img-thumbnail me-1" %>
  <p class="mb-0">
    <%= link_to "#{user.name}", user_path(user), class: "no-decoration d-block"%>
    <span><%= user.username %></span>
  </p>
</li>

app/views/users/create.js.erb
$("#comments").html("<%=j render partial: 'comments/comments', locals: {commentable: @commentable}%>")

app/views/users/index.html.erb
<div>
  <% @users.each do |user|%>
    <div>
      <h1><%= user.name %><h1>
      <%= image_tag user.avatar_url %>
      <%= link_to "follow", follow_user_path(user), method: :post %>
    </div>
  <% end %>
<div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h3>Comments</h3>

<%= render partial: 'comments/form', locals: {commentable: @user }%>

<%= render @user.comments.where(parent_id: nil) %>