config/routes.rb
Rails.application.routes.draw do
  resources :events
  root to: "posts#index"
  devise_for :users

  resources :users do
    member do
      post :follow
    end
    resources :comments, module: :users 
  end

  resources :posts do
    member do
      post :bookmark
    end
    resource :like, module: :posts
    resources :comments, module: :posts
  end


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/header/_navbar.html.erb
<nav class="collapse navbar-collapse order-3 order-lg-1" id="navmenu">
  <ul class="navbar-nav text-center m-auto">
    <li class="nav-item">
       <%= link_to "Events", events_path, class: 'nav-link' %> 
    </li>
    <li class="nav-item">
      <%= link_to "Users", users_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to "Posts", posts_path, class: 'nav-link' %>
    </li>
  </ul>
</nav>

app/views/layouts/header/_user_session.html.erb
<div class="order-2">
  <%=user_session %>

<div>

app/views/layouts/header/index.html.erb
<header class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container">
    <%= link_to 'Popsty', root_path, class: 'navbar-brand order-1 order-lg-0' %>
    <button 
    class='navbar-toggler order-0' 
    type="button" 
    data-bs-toggle="collapse" 
    data-bs-target="#navmenu">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= render 'layouts/header/navbar' %>
    <%= render 'layouts/header/user_session' %>
  </div>
</header>