config/routes.rb
Rails.application.routes.draw do
  resources :events
  root to: "posts#index"
  devise_for :users

  resources :users do
    member do
      post :follow
    end
    resources :comments, module: :users 
  end

  resources :posts do
    member do
      post :bookmark
    end
    resource :like, module: :posts
    resources :comments, module: :posts
  end


  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, as: :commentable
  has_many :events, as: :eventable, dependent: :destroy
  validates :title, :description, presence: true

  def mentions
    @mentions ||= begin
                  regex = /@([\w]+)/
                  description.scan(regex).flatten!
                end
  end

  def mentioned_users
    @mentioned__users ||= User.where(name: mentions)
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post
  def create
    if current_user
    @post.likes.where(user_id: current_user.id).first_or_create
    respond_to do |format|
      format.html {redirect_to @post}
      format.js 
    end
    else 
      redirect_to :new_user_session
    end
  end

  def destroy
    @post.likes.where(user_id: current_user.id).destroy_all
    respond_to do |format|
      format.html {redirect_to @post}
      format.js 
    end
  end

  private

  def authenticate_user!
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy bookmark ]
  before_action :verify_owner, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]
  # GET /posts or /posts.json
  def index
    @post = Post.new
    @users = User.take(10)
    @posts = Post.order(created_at: :desc).all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: "Post was successfully created." }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
        format.js
      end
  end
  
  def bookmark
    current_user.events.create(action: "bookmarked", eventable: @post)
    redirect_to  posts_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def verify_owner
      unless @post.user_id == current_user.try(:id)
        render json: {message: ["Unauthorized"]}, status: :unauthorized
      end
    end
    
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_errors.html.erb
<% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: false, html: {class: "w-75 m-auto p-3 pb-0 border rounded bg-light", id: "post_form_#{post.try(:id)}"}) do |form| %>
  <%= render partial: 'errors', locals: {post: post}%>

  <div class="field">
    <%= form.text_field :title, placeholder: "Title", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.text_area :description, placeholder: "Description", class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit submit_text, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_likes.html.erb
<span><%= post.likes.size %></span>

<span><%= like_button(post) %></span>

<%post.likes.each do |like|%>
  <span><%= image_tag like.user.avatar_url, width: 20, class: 'border border-info align-text-top' %></span>
<%end%>

app/views/posts/_post.html.erb
<article id="post_<%= post.id %>" class="card my-2 m-auto w-75">
  <div class="card-body">
  <span class="fw-bold text-secondary"><%= post.user.name %></span>
    <div class="d-flex justify-content-between align-items-center">
      
      <h2 class="card-title">
        <%= link_to "#{post.title}", post, class: "no-decoration"%>
      </h2>
      <div class="dropdown text-nowrap">
        <%= link_to bookmark_post_path(post), method: :post, class:
        "no-decoration" do%>
        <button type="button" class="btn btn-light">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            fill="currentColor"
            class="bi bi-bookmark"
            viewBox="0 0 16 16"
          >
            <path
              d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"
            />
          </svg>
        </button>
        <% end %> <% if post.user_id == current_user.try(:id) %>
        <button
          type="button"
          class="btn btn-light"
          id="moreDropdown"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            fill="currentColor"
            class="bi bi-three-dots"
            viewBox="0 0 16 16"
          >
            <path
              d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"
            />
          </svg>
        </button>
        <% end %>

        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="moreDropdown"
        >
          <li>
            <%= link_to 'Edit', edit_post_path(post), class: "dropdown-item", remote: true %>
          </li>
          <li>
            <%= link_to 'Destroy', post, method: :delete, class: "dropdown-item", remote: true %>
          </li>
        </ul>
      </div>
    </div>
    <p><%= markdownify post.description %></p>
    <div id="<%= post.id %>_likes" class="text-end">
      <%= render partial: "likes", locals: {post: post} %>
    </div>
  </div>
</article>

app/views/posts/create.js.erb
$('#posts').prepend("<%=j render @post %>")
$('#post_form_').trigger("reset")

app/views/posts/destroy.js.erb
$("#post_<%= @post.id%>").remove()

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/edit.js.erb
$("#post_<%= @post.id%>").replaceWith("<%=j render partial: 'form', locals: {post: @post, submit_text: 'Save'}%>")

app/views/posts/index.html.erb
<div class="row container mt-3 m-auto g-0">
  <% if user_signed_in? %>
     <section class="col-12 row g-0">
      <div class="col-8 ">
        <%= render partial: 'form', locals: {post: @post, submit_text: "Create"}%>
      </div>
      <div class="col-4 border">
      </div>
    </section>
  <% end %>
  <section id="posts" class="col-8">
    <%= render @posts%>  
  </section>
  

  <aside class="border col-4">
    <ul>
      <%= render @users %>
    </ul>
  </aside>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= markdownify @post.description %>
</p>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<div id="<%= @post.id %>_likes">
  <%= render partial: "likes", locals: {post: @post} %>
</div>

<h3>Comments</h3>

<%= render partial: 'comments/form', locals: {commentable: @post }%>

<%= render @post.comments.where(parent_id: nil) %>

app/views/posts/update.js.erb
$("#post_form_<%= @post.id %>").replaceWith("<%=j render @post %>")